FROM free5gc/base:latest AS builder
FROM registry.access.redhat.com/ubi8/ubi:latest

LABEL description="Free5GC open source 5G Core Network" \
    version="Stage 3"

ENV F5GC_MODULE free5gc-upfd
ENV DEBIAN_FRONTEND noninteractive
ARG DEBUG_TOOLS

# Install debug tools ~ 100MB (if DEBUG_TOOLS is set to true)
RUN if [ "$DEBUG_TOOLS" = "true" ] ; then yum -y update && yum -y install vim strace net-tools iputils nmap-ncat ; fi

# Install UPF dependencies
RUN yum -y update \
    && yum -y install libmnl libyaml iproute iptables \
    && yum -y clean all

# Set working dir
WORKDIR /free5gc
RUN mkdir -p ${F5GC_MODULE}/config/

# Copy executable and default configuration
COPY --from=builder /free5gc/${F5GC_MODULE} ./${F5GC_MODULE}/

# Copy linked libs
COPY --from=builder /free5gc/libgtp5gnl.so.0 /lib64/
COPY --from=builder /free5gc/liblogger.so /lib64/

# Move to the executable location
WORKDIR /free5gc/${F5GC_MODULE}

# Update links
RUN ldconfig
