CONTAINER_IMAGE_OWNER = 'free5gc'
CONTAINER_IMAGE_NAME = 'base'
CONTAINER_IMAGE_TAG = 'latest'

.PHONY: docker podman
docker:
	docker build -t ${CONTAINER_IMAGE_OWNER}/${CONTAINER_IMAGE_NAME}:${CONTAINER_IMAGE_TAG} ./base
	docker image ls ${CONTAINER_IMAGE_OWNER}/${CONTAINER_IMAGE_NAME}:${CONTAINER_IMAGE_TAG}

podman:
	podman build -t ${CONTAINER_IMAGE_OWNER}/${CONTAINER_IMAGE_NAME}:${CONTAINER_IMAGE_TAG} ./base
	podman image ls ${CONTAINER_IMAGE_OWNER}/${CONTAINER_IMAGE_NAME}:${CONTAINER_IMAGE_TAG}

